### PR TITLE
Update to AF2 version 2.3.1

### PR DESCRIPTION
**Pull request by PasqM**

### CODE REVIEW

**Comment by sanjaysrikakulam** [comment]
Hi @PasqM 

Thank you for the PR. I am just back from vacation. I will go through this ASAP.

**Comment by Old-Shatterhand** [comment]
Hi @PasqM,

thank you for contributing. We will check the PR shortly and merge it then. May I ask you to update the [API Changes section](https://github.com/kalininalab/alphafold_non_docker/blob/925219eadfb7c6ce116b97852ed8f92d648431eb/README.md#api-changes) in the README as well?

Best, Roman

**Comment by PasqM** [comment]
Hi @Old-Shatterhand, 

I updated it.

Best, Pasquale

**Comment by rocke2020** [comment]
> Hi @PasqM 
> 
> I updated it.

I used your update, works. Thanks very much!!

**Comment by Old-Shatterhand** [comment]
@PasqM thank you for updating. 
@rocke2020 thank you for testing.

I plan to merge the code next week.

Best, Roman

**Comment by sanjaysrikakulam** [comment]
Thank you @PasqM and @Old-Shatterhand

**Pull request merged**
